//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test20230527.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bidding
    {
        public int ID { get; set; }
        public string ProName { get; set; }
        public int ProTypeID { get; set; }
        public string ProAddress { get; set; }
        public string Input { get; set; }
        public System.DateTime Date { get; set; }
        public string Charge { get; set; }
        public string Unit { get; set; }
        public decimal Amount { get; set; }
        public string Contacts { get; set; }
        public string Tel { get; set; }
    }
}
